version: '2'
services:
  web:
    image: hahoo/node-hello:latest
    command: npm start
    ports:
      - 80:8080
    restart: always
    volumes:
      - ./config/app:/usr/src/app/config/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:9.6.2-alpine
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: SgQ6Vhc3u015xOL09se9
      PGDATA: /var/lib/postgresql/data/pgdata
  redis:
    image: redis:3.2.8-alpine
    restart: always
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    command: redis-server /usr/local/etc/redis/redis.conf
